### ISSUE TITLE
Creating new environment in Watson Studio based on custom image not possible with cpdctl

### ISSUE THREAD

**Issue by luca-janas** [IBM/cpdctl#11]
We would like to use cpdctl to create a new environment in Watson Studio based on a custom image that contains python packages needed to execute our automated platform tests. We already use cpdctl to create custom environments in WML, which are then used for our deployment tests.

The creation of a new environment in Watson Studio via UI based on this image works as expected.

We used the following example to implement the creation of new environments in Watson Studio via cpdctl: https://github.com/IBM/cpdctl/blob/master/samples/Notebook-and-Environment-samples-for-Projects.ipynb

An example call of us would look like this:

`cpdctl environment create --project-id xyz --type notebook --name "Default IBM Runtime 22.1 on Python 3.9 (custom)" --display-name "IBM Runtime 22.1 on Python 3.9 (custom)" --hardware-specification '{"guid": "f3ebac7d-0a75-410c-8b48-a931428cc4c5"}' --software-specification '{"guid": "24d8d3f7-ac80-508f-80f9-d86f7140098a"}' --tools-specification '{"supported_kernels": [{"language": "python", "version": "3.9", "display_name": "IBM Runtime 22.1 on Python 3.9 (custom)"}]}' --jmes-query metadata.asset_id --output json`

This creates a new environment in the Watson Studio project, but fails to reference the correct software configuration.  It follows that this environment can not be used to execute our tests due to the job returning that an environment has been used that is no longer available.

![image](https://user-images.githubusercontent.com/112473178/187392760-684fd4d4-89b4-4c76-aa73-ec6bd4c15d27.png)

This has been tested on CP4D 3.5.14 and 4.5.0 on ppc64le.

As far as we know, a software specification is a term used only in WML, not in Watson Studio.  Are we using the tool incorrectly or does cpdctl not support the creation of environments in Watson Studio yet?

Help is greatly appreciated!

**Comment by alexlang74** [comment]
Hi @luca-janas , 
WS _does_ have the concept of software specifications. The UI looks like a SW spec with this guid can't be found on the system, and thus, not rendered.
Are you following all the steps listed in "Demo 4: Adding additional packages for custom environment" of https://github.com/IBM/cpdctl/blob/master/samples/Notebook-and-Environment-samples-for-Projects.ipynb. ? You start by creating a custom software specification, and use then that to create an environment...

**Comment by luca-janas** [comment]
Hi @alexlang74, 

thank you for your answer! 

We do not create a custom software specification with a package extension via cpdctl as shown in the example. We are using an existing custom software specification whose software specification id we query using cpdctl. This existing custom software specification is based on a custom image with additional python packages.  

Here an example for the query to get the id of the custom software specification:

`cpdctl environment software-specification list --project-id xyz --name custom-sw-spec-name --jmes-query resources[0].metadata.asset_id --output json`

This returns the software specification id: 24d8d3f7-ac80-508f-80f9-d86f7140098a

So the software specification we are trying to use already exists. We create a new environment in the project with this software specification with the cpdctl call shown in the original issue statement.

Is it possible to use the existing custom software specification to create a new environment in a project?

**Comment by thomasschaeck** [comment]
Hi @rafalbigaj could you please have a look at this ?

In what time frame can cptctl be extended for this use case ?

**Comment by rafalbigaj** [comment]
@alexlang74 are you able to answer Luca's question?

**Comment by alexlang74** [comment]
Sorry, yes. Looking into this now...

**Comment by alexlang74** [comment]
Have not found a good way with cpdctl yet... What you need in CPD here is the reference for a custom _runtime definition_, which "points" to the custom runtime image. This is different from WML, where "all you need" is a software specification. I'm now checking whether it's possible to specify this definition via cpdctl...

**Comment by alexlang74** [comment]
I need to check whether Rafal can do this, or actually Fang from our team (who is on vac right now)

**Comment by alexlang74** [comment]
So @luca-janas , 
I have not found a way to do this via cpdctl yet. The key thing that is missing is a reference to the _runtime definition_ that you created when you uploaded the custom Watson Studio image. The following flow works (outside cpdctl):

**Assumption:** You followed the steps in https://www.ibm.com/docs/en/cloud-paks/cp-data/4.0?topic=environments-building-custom-images to create a custom image. One part (https://www.ibm.com/docs/en/cloud-paks/cp-data/4.0?topic=images-uploading-changed-configuration) involves uploading the custom runtime configuration for your custom image. One _recommendation_: when creating the custom runtime configuration, change its `display_name` attribute to a custom value. This will allow you to find it better in the steps below.

To create a custom environment that references your custom image:
1. Get the platform access token `curl <CloudPakforData_URL>/v1/preauth/validateAuth -u <username>:<password>` 
2. Store that in the environment variable `TOKEN` 
3. Run `curl -k -H "Authorization: Bearer $TOKEN" "https://${cluster_name}/v2/runtime_definitions" | jq -r ".resources[] | {guid: .metadata.guid, display_name: .entity.display_name}"` 
4. This will return a list of runtime definitions, similar to 
     ``` 
     ...
     {
       "guid": "17f0181e-1840-5e04-bdba-237d53266c0c",
       "display_name": "Jupyterlab Notebook IDE with Python 3.9 and GPU"
     }
     {
       "guid": "8a5849c6-949c-5ac9-ba8f-0b4e07efb107",
      "display_name": "Alex Jupyter with Python 3.7"
    }
    ...
5. Find the guid of your custom runtime definition (this is where a custom display_name comes handy)
6. To create a custom environment, run
    ```
    curl -k -X POST -H "Authorization: Bearer ${TOKEN}" -H "accept:application/json" -H "Content-Type:application/json" -d '{"type": "notebook", "name": "Custom_Py39_Env", "display_name": "Custom Python3.9 environment", "hardware_specification": {"type": "referenced", "guid": "f3ebac7d-0a75-410c-8b48-a931428cc4c5"}, "software_specification": {"type": "referenced", "guid": "12b83a17-24d8-5082-900f-0ab31fbfd3cb"}, "tools_specification": {"supported_kernels": [{"name": "python3", "language": "python", "version": "3.9", "display_name": "Python 3.9"}]}, "runtime_definition": "<YOUR RUNTIME DEFINITION ID">' "https://<YOUR CLUSTER>/v2/environments?project_id=<YOUR PROJECT>"
    ```

**Comment by alexlang74** [comment]
Thanks, @luca-janas , my apologies that this took so long...

**Comment by luca-janas** [comment]
Hi everyone, please excuse my reply. Thank you for providing the API calls and the functionality in cpdctl! We were able to implement our test cases.
