### ISSUE TITLE
add “revision” and "promote" to cpdctl code-package

### ISSUE THREAD

**Issue by Jianbin-IBM** [IBM/cpdctl#16]
Hi, for cpdctl code-package, now we have:

COMMANDS:
  list       List all code packages in a given project or space.
  create     Create a new code package.
  delete     Delete a code package.
  get        Retrieve a code package.
  promote    Promote a code package from a project to a space.
  revision   Commands for Revision resource.

But in the document: https://github.com/IBM/cpdctl/blob/master/README_command_reference.md, we don’t have “revision” and "promote". Any chance we can add it?

Thanks

**Comment by jacek-midura** [comment]
@Jianbin-IBM thank you for reporting this problem, I updated the command reference and now `code-package revision` and `code-package promote` commands are included.
